### PR TITLE
update octave, runtime

### PR DESCRIPTION
**Pull request by kevinsmia1939**

### CODE REVIEW

**Comment by kevinsmia1939** [comment]
I did some test and it seems to work fine.

**Comment by mtmiller** [comment]
I think you can revert the addition of MPFR, I think only one portion of SuiteSparse uses it, and we don't build that library. Can you test that?

**Comment by kevinsmia1939** [comment]
bot, build

**Comment by kevinsmia1939** [comment]
test it a bit, seems to work fine

**Comment by mtmiller** [comment]
Perfect, looks good. Do you want to rebase/squash to clean up a bit? Otherwise I can squash it myself.

**Comment by kevinsmia1939** [comment]
Squash it for me, thanks

**Pull request merged**
