### PR TITLE
Octave5

### PR DESCRIPTION
**Pull request by Alexander-Wilms**

### CODE REVIEW

**Comment by Alexander-Wilms** [comment]
Strange, a local build succeeds.

**Comment by mtmiller** [comment]
@Alexander-Wilms should we merge this now? Or would you like to leave this off master until the official RC1 comes out?

**Comment by Alexander-Wilms** [comment]
Personally, I'd wait until RC1. People can still easily test it using the repo-test instance of Flathub.

**Comment by mtmiller** [comment]
This should be ok to merge to master whenever you want, it builds the official rc1 now. Tested locally, builds and runs fine for me.

**Comment by Alexander-Wilms** [comment]
Great, I've merged it

**Pull request merged**
