### PR TITLE
include PKG_CONFIG_PATH in the environment

### LINKED ISSUE #137: pkg-config doesn't find bundled libs automatically
With the latest stable build of Octave:

```
$ flatpak run org.octave.Octave --silent --eval "system ('pkg-config --libs octave');"
Package octave was not found in the pkg-config search path.
Perhaps you should add the directory containing `octave.pc'
to the PKG_CONFIG_PATH environment variable
Package 'octave', required by 'virtual:world', not found
```

The desired behavior, with `PKG_CONFIG_PATH` set correctly:

```
$ flatpak run org.octave.Octave --silent --eval "system ('pkg-config --libs octave');"
-L/app/lib/octave/6.2.0 -loctave 
```

We should configure this by default so users building custom oct files or installing packages get a working pkg-config setup.

### PR DESCRIPTION
**Pull request by mtmiller**
Fixes #137

### CODE REVIEW

**Comment by mtmiller** [comment]
@Alexander-Wilms I'm at a loss here, do you know what's up with this cmake error? Doesn't look related to my change at all.

**Comment by Alexander-Wilms** [comment]
Yeah, the finish-args shouldn't affect the way the modules are built.

**Comment by Alexander-Wilms** [comment]
bot, build

**Comment by Alexander-Wilms** [comment]
Hm, no idea. I compared the output of the latest commit on the master branch to the output of this PR and there's no significant difference:

Latest master:
```
Running: cmake -GNinja --build build
FB: Running: flatpak build --die-with-parent --env=FLATPAK_BUILDER_BUILDDIR=/run/build/qhull --nofilesystem=host --filesystem=/srv/buildbot/worker/build-x86_64-5/build/.flatpak-builder/build/qhull-1 --bind-mount=/run/build/qhull=/srv/buildbot/worker/build-x86_64-5/build/.flatpak-builder/build/qhull-1 --build-dir=/run/build/qhull --bind-mount=/run/ccache=/srv/buildbot/worker/build-x86_64-5/build/.flatpak-builder/ccache --unshare=network --env=SOURCE_DATE_EPOCH=1618089791 '--env=CFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection ' '--env=CXXFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection ' '--env=LDFLAGS=-L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed ' --env=PYTHON=python3 --env=PATH=/app/bin:/usr/bin:/usr/lib/sdk/openjdk11/bin --env=CCACHE_DIR=/run/ccache/disabled --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --env=FLATPAK_BUILDER_N_JOBS=48 /srv/buildbot/worker/build-x86_64-5/build/.flatpak-builder/rofiles/rofiles-u2x9sZ /bin/sh -c 'cmake -GNinja --build build'
```

This PR:
```
Running: cmake -GNinja --build build
FB: Running: flatpak build --die-with-parent --env=FLATPAK_BUILDER_BUILDDIR=/run/build/qhull --nofilesystem=host --filesystem=/srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/build/qhull-1 --bind-mount=/run/build/qhull=/srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/build/qhull-1 --build-dir=/run/build/qhull --bind-mount=/run/ccache=/srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/ccache --unshare=network --env=SOURCE_DATE_EPOCH=1618438615 '--env=CFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection ' '--env=CXXFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection ' '--env=LDFLAGS=-L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed ' --env=PYTHON=python3 --env=PATH=/app/bin:/usr/bin:/usr/lib/sdk/openjdk11/bin --env=CCACHE_DIR=/run/ccache/disabled --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --env=FLATPAK_BUILDER_N_JOBS=48 /srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/rofiles/rofiles-HAWalM /bin/sh -c 'cmake -GNinja --build build'
```

**Comment by mtmiller** [comment]
Hmm, possibly because the sdk was just updated to cmake version 3.20.0? Something different in the syntax? I know next to nothing about cmake.

**Comment by Alexander-Wilms** [comment]
The module preceding qhull is gl2ps, which also uses cmake, without issue. The difference is that gl2ps uses the "buildsystem: cmake" option and for qhull I used the "buildsystem: simple" option and copied the build commands from the Arch PKGBUILD, since otherwise libqhull is not built.

May that makes a difference.

**Pull request merged**
