### PR TITLE
Test for recent Octave stable version to work.

### PR DESCRIPTION
**Pull request by siko1056**

### CODE REVIEW

**Comment by mtmiller** [comment]
@siko1056 Would you like to try adding `/share/icons/hicolor/1024x1024` to the cleanup list and see if that fixes the build?

**Comment by siko1056** [comment]
Adding

```
cleanup:
- /share/icons/hicolor/1024x1024
```

solves the problem.  Closing test PR.

**Comment by mtmiller** [comment]
@siko1056 Very nice. Can you submit a new PR to add just the cleanup change? This would have no effect now, but makes for fewer change to the manifest to build the stable or default branches of Octave.

**Comment by siko1056** [comment]
@mtmiller you are right, done with #76 .

**Pull request closed without merging**
