### PR TITLE
Update to Octave version 5.2.0, closes #89.

### LINKED ISSUE #89: update to Octave 5.2.0
Will be released later this week. A beta release 5.1.90 is available now for testing.

### PR DESCRIPTION
**Pull request by siko1056**

### CODE REVIEW

**Comment by mtmiller** [comment]
Great, thank you!

I get 9 test failures in data.cc, that I don't get running natively, and I don't think I saw these before. Can you verify?

**Comment by mtmiller** [comment]
Nevermind, I do see the same test failures in 5.1.0, not new.

**Comment by siko1056** [comment]
@mtmiller I also see the 8 test failures in 5.1.0 and 5.2.0

```
libinterp/corefcn/data.cc-tst .................................. PASS 1137/1151
                                                                 FAIL    8
```

Additionally, both build die on testing the audio

```
libinterp/dldfcn/audiodevinfo.cc-tst ...........................ALSA lib ../../src/conf.c:3956:(snd_config_update_r) Cannot access file /etc/alsa-pulse.conf
octave-gui: src/hostapi/alsa/pa_linux_alsa.c:1453: BuildDeviceList: Assertion `devIdx < numDeviceNames' failed.
fatal: caught signal Aborted -- stopping myself...
```

**Comment by mtmiller** [comment]
@siko1056 Can you report the audiodevinfo assertion failure? I don't see it on my system. I reported the failing complex data tests as #93.

**Pull request merged**
