### PR TITLE
remove --filesystem=xdg-config/kdeglobals:ro

### PR DESCRIPTION
**Pull request by eszlari**
not needed since KDE runtime 5.12

### CODE REVIEW

**Comment by mtmiller** [comment]
Have you tested this with an older Plasma desktop, e.g. Ubuntu 18.04 with Plasma 5.12? I don't use KDE, but I did a little searching and found [this blog post](https://jgrulich.cz/2019/01/08/integration-of-sandboxed-qt-applications/) and [this git log](https://cgit.kde.org/xdg-desktop-portal-kde.git/log/?ofs=50), indicating that the host needs Plasma 5.15 for this to be safely dropped.

**Comment by eszlari** [comment]
> Have you tested this with an older Plasma desktop, e.g. Ubuntu 18.04 with Plasma 5.12? I don't use KDE, but I did a little searching and found [this blog post](https://jgrulich.cz/2019/01/08/integration-of-sandboxed-qt-applications/) and [this git log](https://cgit.kde.org/xdg-desktop-portal-kde.git/log/?ofs=50), indicating that the host needs Plasma 5.15 for this to be safely dropped.

Quote from that blog post:

> These tweaks have been usually set in the runtimes and applications using these runtimes automatically inherited all the needed permissions during the build.

https://invent.kde.org/kde/flatpak-kde-runtime/-/blob/38c19ccfd07695051c8a8eb51df86137232eae4d/org.kde.Sdk.json.in#L72

**Comment by mtmiller** [comment]
Also from that blog post:

> This support will be also released with Plasma 5.15 in february.
> […]
> Hopefully with all of this released soon and more widely used, we can slowly start removing all the hardcoded permissions for both dconf and kdeglobals config file in the runtimes.

**Comment by TingPing** [comment]
You are complicating the situation.

This permission was simply added to the runtime. Applications can thus remove it. Nothing about KDE is relevant to that.

**Comment by mtmiller** [comment]
Thank you for clarifying. This was not at all clear from the original submission or the commit message.

I've reworded and merged this via #102. 

Thanks @eszlari!

**Pull request closed without merging**
